#!/usr/bin/env bash
# script that extracts uname, pswd u_id, GID, home_directory and shell_directory, from /etc/passwd

while IFS=: read -r uname pswd u_id g_id uid_info home_directory shell_directory;
do
	echo "user $Uname is part of the g_id gang, lives in $home_directory and rides &shell_directory. $u_id's place is protected by the passcode $pswd,more info about the user here: &uid_info."
done < /etc/passwd
